In [1]:
import pandas as pd

## 구별 통합

In [189]:
df1 = pd.read_csv('(전처리)주민등록인구_2022.csv')             # 2022
df2 = pd.read_csv('자치구별_예산_2021.csv')                  # 2021
df3 = pd.read_csv('인구이동(구별)_2022.csv')                 # 2022
df4 = pd.read_csv('상주_유입인구_2020.csv', index_col=0)     # 2020 
df5 = pd.read_csv('(전처리)사업체분포(다수업종_동별).csv')       # 2021
df6 = pd.read_csv('상권_2021.csv')                         # 2021

# 필요한 열만
df1 = df1[['자치구', '세대 (세대)', '계', '세대당인구.2']]
df1.columns = ['자치구', '총 세대수', '총 인구수', '세대당인구']
df2 = df2[['자치구', '총 예산', '주차장사업비']]
df3 = df3[['자치구', '순이동']]
df5 = df5.drop(['행정동'], axis=1)
df5 = df5.iloc[:, [0, 2, 3, 6, 7, 9, 11, 13, 15, 17, 19]]
df5.columns = ['자치구', '택시운송업', '한식_일반_음식점업', '용달_화물자동차_운송업',
               '부동산_중개_및_대리업', '두발미용업', '커피전문점', '기타_주점업',
               '남녀용_겉옷_및_셔츠_도매업', '일반_교과_학원', '한식_육류요리_전문점']

df5.iloc[:, 1:] = df5.iloc[:, 1:].astype(str)
for i in range(1, 11):
    df5.iloc[:, i] = df5.iloc[:, i].str.replace('-', '0')
df5.iloc[:, 1:] = df5.iloc[:, 1:].astype(int)
df5 = df5.groupby('자치구', as_index=False)[['택시운송업', '한식_일반_음식점업', '용달_화물자동차_운송업',
                                            '부동산_중개_및_대리업', '두발미용업', '커피전문점', '기타_주점업',
                                            '남녀용_겉옷_및_셔츠_도매업', '일반_교과_학원', '한식_육류요리_전문점']].sum()
df6 = df6.iloc[:, [4, 5]]
df6.columns = ['총상권개수', '자치구']
df6 = df6.groupby('자치구', as_index=False)[['총상권개수']].sum()

# merge
df_gu = pd.merge(df1, df2, on='자치구', how='outer')
df_gu = pd.merge(df_gu, df3, on='자치구', how='outer')
df_gu = pd.merge(df_gu, df4, on='자치구', how='outer')
df_gu = pd.merge(df_gu, df5, on='자치구', how='outer')
df_gu = pd.merge(df_gu, df6, on='자치구', how='outer')

# 저장
df_gu.to_csv('자치구별_주민등록_예산_인구이동_사업체_상권.csv', index=False, encoding='cp949')

# 불러오기
df = pd.read_csv('자치구별_주민등록_예산_인구이동_사업체_상권.csv', encoding='cp949')
df

/var/folders/hg/x3d2zgf505lcqckgrdxxb2z00000gn/T/ipykernel_11000/3943048916.py:22: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df5.iloc[:, 1:] = df5.iloc[:, 1:].astype(int)

,자치구,총 세대수,총 인구수,세대당인구,총 예산,주차장사업비,순이동,총상주인구(명),총유입인구(명),통근_유입인구(명),통학_유입인구(명),총유출인구(명),통근_유출인구(명),통학_유출인구(명),총주간인구(명),주간인구지수(%),택시운송업,한식_일반_음식점업,용달_화물자동차_운송업,부동산_중개_및_대리업,두발미용업,커피전문점,기타_주점업,남녀용_겉옷_및_셔츠_도매업,일반_교과_학원,한식_육류요리_전문점,총상권개수
0,종로구,75003,158996,1.95,50435,49036,-1433,141316,236168,215753,20415,31687,27898,3789,345797,245,187,1568,671,605,266,1027,576,509,139,405,77
1,중구,63686,134635,1.91,49318,47678,-727,118450,289569,273093,16476,27795,24388,3407,380224,321,219,1556,688,664,333,934,396,10658,72,382,80
2,용산구,113093,244645,1.99,31727,30678,-1279,212043,113823,103603,10220,60758,55127,5631,265108,125,545,883,601,929,396,694,514,94,134,281,57
3,성동구,135870,300505,2.11,18122,17731,-4015,282193,121304,105715,15589,85702,77763,7939,317795,113,2034,975,1222,923,517,718,312,265,318,372,55
4,광진구,167427,360109,1.99,19431,19026,-1210,334190,78921,60920,18001,112066,102899,9167,301045,90,1566,1055,1010,976,765,698,612,133,461,452,62
5,동대문구,167598,357014,1.98,23669,22368,1166,331973,105085,85341,19744,87836,78326,9510,349222,105,1926,1338,1618,921,646,613,430,334,384,395,77
6,중랑구,185920,399562,2.06,21281,17855,-160,377150,43417,38814,4603,110919,101838,9081,309648,82,4454,1043,2038,813,789,470,504,112,371,485,61
7,성북구,195396,447056,2.18,18198,15423,2039,425639,92714,55350,37364,119879,108350,11529,398474,94,2089,992,1385,940,772,597,443,163,631,363,76
8,강북구,145896,311569,2.03,13140,10754,-3121,293755,36465,32774,3691,86573,77911,8662,243647,83,2245,1017,988,641,680,443,542,57,300,333,63
9,도봉구,139114,327361,2.25,11853,9099,-3567,311839,34613,30287,4326,94550,84905,9645,251902,81,5130,670,1636,565,610,355,268,36,427,320,43
10,노원구,218270,527032,2.32,19055,11662,-4875,504411,76609,53906,22703,146125,133473,12652,434895,86,5314,924,1635,789,808,591,334,74,1080,393,42
11,은평구,213914,484043,2.18,21000,20003,-3523,456474,39435,36556,2879,142846,132063,10783,353063,77,3822,1003,1373,1298,977,579,477,50,687,439,68
12,서대문구,144838,322952,2.10,22080,19206,3574,304192,103785,67662,36123,87563,79456,8107,320414,105,2249,890,1071,758,598,470,460,47,435,312,62
13,마포구,178482,381858,2.02,84194,68378,-2448,354420,182226,165207,17019,108630,97848,10782,428016,121,1697,1519,1303,1318,1023,1614,1053,143,579,647,77
14,양천구,180633,457781,2.43,41798,30418,-4753,431427,54767,52477,2290,132112,118781,13331,354082,82,4491,859,1848,1022,850,504,398,57,1500,292,56
15,강서구,266982,585901,2.08,17211,15268,-3444,555402,130856,125420,5436,147505,135761,11744,538753,97,6180,1430,2853,1548,1072,906,754,118,846,594,70
16,구로구,180531,432488,2.15,11060,10440,-489,392040,134257,127417,6840,120595,111860,8735,405702,104,3095,1102,1566,890,761,529,540,140,453,399,60
17,금천구,114715,247835,1.92,13232,12434,-217,224123,123049,121599,1450,58969,54593,4376,288203,129,2068,941,1045,836,499,473,351,237,203,309,45
18,영등포구,184714,407367,1.99,30897,29587,-292,360059,253420,249206,4214,99263,90172,9091,514216,143,1863,1846,2234,1271,737,1000,632,138,375,491,98
19,동작구,184229,401572,2.05,19867,18650,-3248,377366,77725,55279,22446,120652,110134,10518,334439,89,1000,798,813,947,661,533,393,19,523,309,57
20,관악구,274811,509803,1.72,15850,15021,3452,479969,62067,48169,13898,157792,146611,11181,384244,80,2653,1327,1656,1112,898,702,624,75,452,425,74
21,서초구,173502,429025,2.41,47048,45979,-6066,394955,269918,257915,12003,111171,98430,12741,553702,140,688,1535,1847,1823,692,1086,427,220,925,413,78
22,강남구,234872,544055,2.27,41187,39268,-1503,499028,575719,561357,14362,113147,99969,13178,961600,193,1668,2749,1017,3251,1406,1789,825,589,1859,822,103
23,송파구,281959,673926,2.31,53945,53152,2126,631722,180409,176194,4215,177642,159981,17661,634489,100,4193,1729,3352,1997,1196,1189,653,226,1045,641,70
24,강동구,196499,463998,2.28,31002,28584,-1327,436710,66435,63873,2562,127012,116026,10986,376133,86,3836,1150,1677,1324,933,686,538,110,827,419,60

## 행정동별

In [23]:
pd.set_option('display.max_columns', None)

df1 = pd.read_csv('지하철총승객수_2022.csv')
df2 = pd.read_csv('인구이동(동별)_2022.csv')
df3 = pd.read_csv('사업체(사업대분류별)_2021.csv')
df4 = pd.read_csv('(전처리)사업체분포(다수업종_동별).csv')
df5 = pd.read_csv('버스정류장_승하차총개수_2022.csv')
df6 = pd.read_csv('상권_2021.csv')
df7 = pd.read_csv('주택종류별_행정동별_2020.csv')

# 필요한 열만
df1 = df1[['승차총승객수', '하차총승객수', '행정동']]
df2 = df2[['행정동', '순이동']]
df3 = df3.iloc[:, [0, 1, 2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]]
df3.columns = ['행정동', '사업체수', '종사자수', '농업 임업 및 어업', '광업', '제조업',
               '전기 가스 증기 및 공기조절 공급업', '수도 하수 및 폐기물 처리 원료 재생업', '건설업',
               '도매 및 소매업', '운수 및 창고업', '숙박 및 음식점업', '정보통신업',
               '금융 및 보험업', '부동산업', '전문 과학 및 기술 서비스업',
               '사업시설 관리 사업 지원 및 임대 서비스업', '공공행정 국방 및 사회보장 행정',
               '교육 서비스업', '보건업 및 사회복지 서비스업', '예술 스포츠 및 여가관련 서비스업',
               '협회 및 단체 수리 및 기타 개인 서비스업']
df4 = df4[df4['자치구'] == '강서구'].reset_index(drop=True)
df4 = df4.iloc[:, [1, 3]]
df4.columns = ['행정동', '택시운송업']
df6 = df6[df6['시군구명'] == '강서구'].reset_index(drop=True)
df6 = df6.iloc[:, [4, 6]]
df6.columns = ['총상권개수', '행정동']

# 지하철 승차총승객수 행정동별로
df1 = df1.groupby('행정동', as_index=False)[['승차총승객수', '하차총승객수']].sum()

# merge
df_dong = pd.merge(df1, df2, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df3, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df4, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df5, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df6, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df7, on='행정동', how='outer')
df_dong = df_dong.fillna(0)

# 저장
df_dong.to_csv('행정동별_지하철_인구이동_사업체_버스_상권.csv', index=False, encoding='cp949')

# 불러오기
df = pd.read_csv('행정동별_지하철_인구이동_사업체_버스_상권.csv', encoding='cp949')
df

,행정동,승차총승객수,하차총승객수,순이동,사업체수,종사자수,농업 임업 및 어업,광업,제조업,전기 가스 증기 및 공기조절 공급업,수도 하수 및 폐기물 처리 원료 재생업,건설업,도매 및 소매업,운수 및 창고업,숙박 및 음식점업,정보통신업,금융 및 보험업,부동산업,전문 과학 및 기술 서비스업,사업시설 관리 사업 지원 및 임대 서비스업,공공행정 국방 및 사회보장 행정,교육 서비스업,보건업 및 사회복지 서비스업,예술 스포츠 및 여가관련 서비스업,협회 및 단체 수리 및 기타 개인 서비스업,택시운송업,버스승차총승객수,버스하차총승객수,총상권개수,총주택수,총단독주택,일반단독주택,다가구주택,영업겸용주택,아파트,연립주택,다세대주택,비거주용건물내주택
0,가양1동,13109727.0,13064365.0,-31,9982,70656,1,0,289,10,10,360,2442,1360,1309,823,204,671,1003,354,3,225,171,199,548,370,4074922,4032289,4.0,7921,84,14,42,28,6733,359,713,32
1,가양2동,6819679.0,6616341.0,-12,914,3352,0,0,14,3,2,49,257,151,65,38,9,51,45,29,2,27,60,24,88,44,621276,618379,0.0,7085,0,0,0,0,7082,0,0,0
2,가양3동,2275811.0,2195541.0,-390,1252,7941,0,0,77,0,1,48,352,278,48,90,2,72,94,43,2,39,27,15,64,116,715743,753678,1.0,7454,0,0,0,0,7454,0,0,0
3,공항동,3147635.0,3090108.0,-423,2838,34394,1,0,105,4,5,142,788,559,347,75,20,138,87,91,7,101,70,76,222,307,2674705,2394296,6.0,7888,1329,152,822,355,3044,133,3319,63
4,방화1동,4046006.0,3895496.0,-230,3658,11304,0,0,120,1,1,170,923,607,392,109,21,223,150,100,2,241,143,105,350,225,1513860,1526400,6.0,13673,916,112,628,176,10024,144,2499,90
5,방화2동,10425835.0,9578946.0,-54,3860,16238,0,0,83,3,6,161,885,1683,344,51,8,118,58,59,6,54,59,65,217,1644,1594059,1487790,5.0,7532,1218,338,737,143,3922,196,2086,110
6,방화3동,2181877.0,2095015.0,-255,1287,4689,0,0,24,1,7,62,319,343,102,50,8,61,60,30,4,59,36,23,98,385,488663,521600,2.0,9698,117,0,94,20,8921,90,556,14
7,염창동,9343626.0,8982981.0,-173,3097,16227,0,0,105,7,5,137,814,434,266,202,36,256,155,72,2,199,92,96,219,436,4343275,3710286,2.0,13248,86,9,43,34,11882,216,1015,49
8,우장산동,11283398.0,11478472.0,-123,2508,7147,0,0,48,1,1,291,577,328,224,90,16,157,76,45,1,246,109,72,226,126,3188889,3537893,4.0,13395,431,27,296,108,9529,324,3040,71
9,화곡8동,9439227.0,8992417.0,-240,1748,4385,0,0,59,1,0,90,549,209,222,45,14,111,47,39,1,49,70,47,195,86,2699545,2548803,2.0,9035,652,71,448,133,734,329,7273,47
10,화곡본동,9267998.0,8608967.0,-364,2177,4919,0,0,72,2,4,132,569,319,283,86,14,115,72,60,2,103,96,51,197,129,2859195,2684232,3.0,12605,730,120,456,154,1064,630,10103,78
11,등촌1동,0.0,0.0,460,2720,17753,0,0,112,0,3,129,753,243,327,182,25,234,193,74,3,83,81,74,204,263,2439846,3058086,3.0,6384,183,16,109,58,4633,143,1382,43
12,등촌2동,0.0,0.0,-507,1211,3972,0,0,51,0,0,74,338,168,115,55,4,62,56,40,4,66,34,24,120,165,2405307,2691130,2.0,7009,491,60,352,79,2717,472,3291,38
13,등촌3동,0.0,0.0,-517,3261,20336,1,0,79,1,3,115,1027,403,370,125,40,214,145,106,3,185,138,79,227,320,3703534,4098849,4.0,13522,10,0,0,6,13287,0,211,14
14,화곡2동,0.0,0.0,-256,1283,2827,0,0,55,0,0,78,480,195,78,49,5,59,38,25,1,66,29,24,101,78,1576634,1298346,2.0,6093,661,54,488,119,338,96,4930,68
15,화곡3동,0.0,0.0,19,1690,4397,0,0,56,1,1,93,348,211,271,49,16,116,59,43,2,117,69,76,162,72,1365746,1592028,2.0,6665,478,24,370,84,3463,108,2580,36
16,화곡4동,0.0,0.0,-226,1928,4315,0,0,87,0,1,125,591,232,275,44,10,90,61,34,2,63,56,67,190,107,1660224,1668659,5.0,7053,831,60,587,184,694,179,5270,79
17,화곡6동,0.0,0.0,228,2456,12040,0,0,73,0,3,149,557,302,481,73,22,156,138,62,6,66,78,96,194,477,4602265,3933868,6.0,8085,560,44,391,125,3117,692,3641,75
18,발산1동,0.0,0.0,-377,6786,32771,2,0,207,3,11,316,2244,693,542,457,79,368,564,214,4,405,181,108,388,635,4610005,3727144,4.0,12284,242,8,184,50,9143,470,2389,40
19,화곡1동,0.0,0.0,27,4150,10810,0,0,249,0,5,290,1018,470,718,108,17,243,117,103,4,111,136,158,403,195,5984997,6237087,7.0,18754,1240,118,831,291,5986,213,11128,187

In [4]:

df1 = pd.read_csv('지하철총승객수_2022.csv')
df2 = pd.read_csv('인구이동(동별)_2022.csv')
df3 = pd.read_csv('사업체(사업대분류별)_2021.csv')
df4 = pd.read_csv('(전처리)사업체분포(다수업종_동별).csv')
df5 = pd.read_csv('버스정류장_승하차총개수_2022.csv')
df6 = pd.read_csv('상권_2021.csv')
df7 = pd.read_csv('주택종류별_행정동별_2020.csv')

In [6]:
df8 = pd.read_csv('(행정동별 통합) 자동차, 주차장, 불법주차.csv')
df8

,행정동명,주차장 개수,주차장 면수,공영 개수,공영 면수,민영 개수,민영 면수,노상 개수,노상 면수,노상 시영 개수,노상 시영 면수,노상 구영 개수,노상 구영 면수,노외 개수,노외 면수,노외 시영 개수,노외 시영 면수,노외 구영 개수,노외 구영 면수,노외 민영 개수,노외 민영 면수,건축물부설 개수,건축물부설 면수,건축물부설 일반주택 개수,건축물부설 일반주택 면수,건축물부설 공동주택 개수,건축물부설 공동주택 면수,건축물부설 일반건축물 개수,건축물부설 일반건축물 면수,공영주차장 수,공영주차장 총 주차면,승용,승합,특수,화물,자동차등록대수,단속건수
0,염창동,421,20668,15,125,406,20543,15,125,0,0,15,125,0,0,0,0,0,0,0,0,406,20543,23,118,153,12299,230,8126,0,0,13948,316,24,1296,15584,7495
1,등촌1동,473,13600,15,214,458,13386,14,203,0,0,14,203,1,11,0,0,1,11,0,0,458,13386,71,236,141,4259,246,8891,0,0,7852,292,23,876,9043,6341
2,등촌2동,759,9611,38,254,721,9357,37,144,0,0,37,144,1,110,0,0,1,110,0,0,721,9357,241,758,349,6913,131,1686,1,90,6203,169,11,619,7002,1888
3,등촌3동,233,17670,12,150,221,17520,12,150,0,0,12,150,3,176,0,0,0,0,3,176,218,17344,6,39,34,7802,178,9503,2,111,8100,278,17,756,9151,2824
4,화곡본동,1877,12732,38,537,1839,12195,35,109,0,0,35,109,4,443,0,0,3,428,1,15,1838,12180,401,1021,1156,8460,281,2699,1,231,7903,323,14,949,9189,4098
5,화곡2동,1052,6412,45,513,1007,5899,44,454,0,0,44,454,1,59,0,0,1,59,0,0,1007,5899,281,595,557,4199,169,1105,2,268,4086,210,13,604,4913,3829
6,화곡3동,785,9879,40,304,745,9575,39,205,0,0,39,205,2,129,0,0,1,99,1,30,744,9545,282,683,287,7262,175,1600,1,99,5683,153,19,555,6410,4245
7,화곡4동,1296,8090,54,376,1242,7714,53,238,0,0,53,238,2,156,0,0,1,138,1,18,1241,7696,458,1062,535,4993,248,1641,3,237,5030,219,15,755,6019,5120
8,화곡6동,1104,14487,55,704,1049,13783,53,374,0,0,53,374,4,382,0,0,2,330,2,52,1047,13731,282,753,412,7325,353,5653,3,390,6888,235,11,772,7906,5820
9,화곡8동,1303,8322,35,521,1268,7801,32,112,0,0,32,112,4,421,0,0,3,409,1,12,1267,7789,298,771,767,5753,202,1265,3,320,5369,186,22,677,6254,3628
10,가양1동,500,49535,14,755,486,48780,11,115,0,0,11,115,5,1096,1,38,2,602,2,456,484,48324,41,179,88,11408,355,36737,2,240,22605,844,31,2281,25761,16889
11,가양2동,44,5314,7,200,37,5114,6,121,0,0,6,121,1,79,1,79,0,0,0,0,37,5114,0,0,7,3278,30,1836,1,79,3805,139,4,358,4306,13315
12,가양3동,40,5567,3,132,37,5435,2,76,0,0,2,76,1,56,1,56,0,0,0,0,37,5435,0,0,10,3012,27,2423,2,136,5558,174,6,562,6300,1801
13,발산1동,742,29360,36,382,706,28978,35,182,0,0,35,182,2,204,0,0,1,200,1,4,705,28974,125,352,307,9575,273,19047,2,224,11632,578,69,1686,13965,20476
14,공항동,1376,25818,55,390,1321,25428,54,379,0,0,54,379,4,70,1,11,0,0,3,59,1318,25369,693,2068,334,6291,291,17010,3,145,8096,561,59,1644,10360,41748
15,방화1동,1013,14206,37,449,976,13757,36,250,1,59,35,191,5,384,1,199,0,0,4,185,972,13572,302,854,296,9325,374,3393,2,209,13081,502,40,1645,15268,6578
16,방화2동,1018,15923,42,1070,976,14853,39,248,0,0,39,248,7,895,3,822,0,0,4,73,972,14780,356,744,300,4801,316,9235,2,804,8071,742,21,1017,9851,7404
17,방화3동,250,8603,18,293,232,8310,15,140,0,0,15,140,3,153,2,135,1,18,0,0,232,8310,85,222,79,6173,68,1915,3,141,6605,273,19,669,7566,2714
18,화곡1동,2458,20220,64,1229,2394,18991,60,534,0,0,60,534,5,705,0,0,4,695,1,10,2393,18981,541,1328,1213,12445,639,5208,4,926,13248,539,39,2097,15923,13410
19,우장산동,895,19795,42,297,853,19498,39,231,0,0,39,231,4,77,0,0,3,66,1,11,852,19487,261,789,376,15582,215,3116,3,68,12701,281,37,992,14011,3073

## 다수업종_동별로 다시

In [20]:
pd.set_option('display.max_columns', None)

df1 = pd.read_csv('지하철총승객수_2022.csv')
df2 = pd.read_csv('인구이동(동별)_2022.csv')
df3 = pd.read_csv('사업체(사업대분류별)_2021.csv')
df4 = pd.read_csv('(전처리)사업체분포(다수업종_동별).csv')
df5 = pd.read_csv('버스정류장_승하차총개수_2022.csv')
df6 = pd.read_csv('상권_2021.csv')

# 필요한 열만
df1 = df1[['승차총승객수', '하차총승객수', '행정동']]
df2 = df2[['행정동', '순이동']]
df3 = df3.iloc[:, [0, 1, 2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]]
df3.columns = ['행정동', '사업체수', '종사자수', '농업 임업 및 어업', '광업', '제조업',
               '전기 가스 증기 및 공기조절 공급업', '수도 하수 및 폐기물 처리 원료 재생업', '건설업',
               '도매 및 소매업', '운수 및 창고업', '숙박 및 음식점업', '정보통신업',
               '금융 및 보험업', '부동산업', '전문 과학 및 기술 서비스업',
               '사업시설 관리 사업 지원 및 임대 서비스업', '공공행정 국방 및 사회보장 행정',
               '교육 서비스업', '보건업 및 사회복지 서비스업', '예술 스포츠 및 여가관련 서비스업',
               '협회 및 단체 수리 및 기타 개인 서비스업']
df4 = df4[df4['자치구'] == '강서구'].reset_index(drop=True)
df4 = df4.iloc[:, [1, 3, 4, 7, 8, 10, 12, 14, 16, 18, 20]]
df4.columns = ['행정동', '택시운송업', '한식_일반_음식점업', '용달_화물자동차_운송업',
               '부동산_중개_및_대리업', '두발미용업', '커피전문점', '기타_주점업',
               '남녀용_겉옷_및_셔츠_도매업', '일반_교과_학원', '한식_육류요리_전문점']
df6 = df6[df6['시군구명'] == '강서구'].reset_index(drop=True)
df6 = df6.iloc[:, [4, 6]]
df6.columns = ['총상권개수', '행정동']

# 지하철 승차총승객수 행정동별로
df1 = df1.groupby('행정동', as_index=False)[['승차총승객수', '하차총승객수']].sum()

# merge
df_dong = pd.merge(df1, df2, on='행정동', how='outer')
#df_dong = pd.merge(df_dong, df3, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df4, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df5, on='행정동', how='outer')
df_dong = pd.merge(df_dong, df6, on='행정동', how='outer')
df_dong = df_dong.fillna(0)

# 저장
df_dong.to_csv('행정동별_지하철_인구이동_사업체(다수업종)_버스_상권.csv', index=False, encoding='cp949')

# 불러오기
df = pd.read_csv('행정동별_지하철_인구이동_사업체(다수업종)_버스_상권.csv', encoding='cp949')
df

,행정동,승차총승객수,하차총승객수,순이동,택시운송업,한식_일반_음식점업,용달_화물자동차_운송업,부동산_중개_및_대리업,두발미용업,커피전문점,기타_주점업,남녀용_겉옷_및_셔츠_도매업,일반_교과_학원,한식_육류요리_전문점,버스승차총승객수,버스하차총승객수,총상권개수
0,가양1동,13109727.0,13064365.0,-31,370,263,666,282,111,204,138,25,19,149,4074922,4032289,4.0
1,가양2동,6819679.0,6616341.0,-12,44,14,69,21,19,6,7,3,2,8,621276,618379,0.0
2,가양3동,2275811.0,2195541.0,-390,116,14,71,15,15,9,1,5,8,-,715743,753678,1.0
3,공항동,3147635.0,3090108.0,-423,307,78,140,67,46,40,52,5,27,29,2674705,2394296,6.0
4,방화1동,4046006.0,3895496.0,-230,225,92,181,112,97,52,27,8,88,34,1513860,1526400,6.0
5,방화2동,10425835.0,9578946.0,-54,1644,76,134,60,48,43,48,5,17,23,1594059,1487790,5.0
6,방화3동,2181877.0,2095015.0,-255,385,19,84,30,30,19,9,1,17,9,488663,521600,2.0
7,염창동,9343626.0,8982981.0,-173,436,57,129,84,53,56,19,12,80,9,4343275,3710286,2.0
8,우장산동,11283398.0,11478472.0,-123,126,47,125,88,73,32,17,-,111,15,3188889,3537893,4.0
9,화곡8동,9439227.0,8992417.0,-240,86,46,75,70,55,19,22,2,18,26,2699545,2548803,2.0
10,화곡본동,9267998.0,8608967.0,-364,129,62,135,64,50,25,40,3,36,32,2859195,2684232,3.0
11,등촌1동,0.0,0.0,460,263,77,70,80,41,58,18,10,20,27,2439846,3058086,3.0
12,등촌2동,0.0,0.0,-507,165,24,69,29,28,20,10,1,19,7,2405307,2691130,2.0
13,등촌3동,0.0,0.0,-517,320,85,113,66,45,53,19,9,78,26,3703534,4098849,4.0
14,화곡2동,0.0,0.0,-256,78,18,75,33,29,17,9,1,34,4,1576634,1298346,2.0
15,화곡3동,0.0,0.0,19,72,47,79,60,57,27,40,2,58,33,1365746,1592028,2.0
16,화곡4동,0.0,0.0,-226,107,60,80,41,54,25,31,-,16,42,1660224,1668659,5.0
17,화곡6동,0.0,0.0,228,477,111,139,64,42,42,94,-,15,39,4602265,3933868,6.0
18,발산1동,0.0,0.0,-377,635,126,243,156,87,105,19,22,161,21,4610005,3727144,4.0
19,화곡1동,0.0,0.0,27,195,114,176,126,92,54,134,4,22,61,5984997,6237087,7.0